"""empty message

Revision ID: 0f81d93898ae
Revises: 8b5cf55e0391
Create Date: 2016-10-01 12:34:41.391139

"""

# revision identifiers, used by Alembic.
revision = '0f81d93898ae'
down_revision = '8b5cf55e0391'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
