"""empty message

Revision ID: 14cc596a5499
Revises: e00bbf4de711
Create Date: 2016-09-26 19:36:09.847533

"""

# revision identifiers, used by Alembic.
revision = '14cc596a5499'
down_revision = 'e00bbf4de711'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lifts',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lifts')
    ### end Alembic commands ###
