"""empty message

Revision ID: e00bbf4de711
Revises: 142ffb76eefd
Create Date: 2016-09-25 17:12:27.094808

"""

# revision identifiers, used by Alembic.
revision = 'e00bbf4de711'
down_revision = '142ffb76eefd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workouts',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workouts')
    ### end Alembic commands ###
